sonar.projectKey=galaxy-github-trending
sonar.projectName=galaxy-github-trending
sonar.projectVersion=2.1.2
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/GitHubTrendingApplication.java
